# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-21 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160921_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
