# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('email', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField()),
                ('replyId', models.IntegerField()),
            ],
        ),
    ]
