# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='email',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='reply',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
